name: Update All Clash Rules
on:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  convert-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 新增：创建目录
      - name: Create rules directory
        run: mkdir -p rules

      # 步骤1：转换直连规则
      - name: Convert Direct List
        run: |
          chmod +x scripts/convert_direct_rule.sh
          ./scripts/convert_direct_rule.sh

      # 步骤2：转换代理规则
      - name: Convert Proxy List
        run: |
          chmod +x scripts/convert_proxy_rule.sh
          ./scripts/convert_proxy_rule.sh

      # 步骤3：转换拦截规则
      - name: Convert Reject List
        run: |
          chmod +x scripts/convert_reject_rule.sh
          ./scripts/convert_reject_rule.sh

      # 步骤4：推送所有生成的规则到仓库
      - name: Upload All Rules
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./rules  # 推送整个rules目录
          publish_branch: main
          keep_files: false
